# Generated by Django 4.2.5 on 2023-09-16 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('quotes', '0001_initial'), ('quotes', '0002_alter_financialobject_category_alter_order_direction'), ('quotes', '0003_alter_accountowner_id_alter_financialobject_id_and_more'), ('quotes', '0004_alter_accountowner_id_alter_financialobject_id_and_more'), ('quotes', '0005_portfolio_name'), ('quotes', '0006_financialobject_ticker')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='FinancialObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Stock', 'Stock'), ('Index', 'Index'), ('ETF', 'Etf'), ('ETFShare', 'Etfshare')], max_length=10)),
                ('isin', models.CharField(max_length=12)),
                ('ticker', models.CharField(blank=True, max_length=12, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quotes.accountowner')),
                ('name', models.CharField(default='', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('direction', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=4)),
                ('price', models.FloatField()),
                ('id_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quotes.financialobject')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quotes.portfolio')),
            ],
        ),
    ]
