# Generated by Django 4.2.5 on 2023-09-16 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0007_auto_20230916_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='nb_items',
            field=models.IntegerField(default=1),
        ),
    ]
