# Generated by Django 4.2.5 on 2023-09-16 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0008_order_nb_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_fee',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.FloatField(default=100),
        ),
    ]
