# Generated by Django 4.2.5 on 2023-10-01 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0009_order_total_fee_alter_order_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('field', models.CharField(choices=[('NAV', 'Nav'), ('Dividends', 'Dividends')], max_length=15)),
                ('value', models.FloatField(default=0)),
                ('origin', models.CharField(choices=[('Yahoo Finance', 'Yf')], max_length=20)),
                ('id_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quotes.financialobject')),
            ],
        ),
    ]
