# Generated by Django 4.2.5 on 2023-11-08 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0010_financialdata'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='financialdata',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='order',
            name='portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='quotes.portfolio'),
        ),
    ]
